// This file is generated by Slice Machine. Update with care!

import FeaturedPost from './FeaturedPost';
import Hero from './Hero';
import PostCard from './PostCard';
import PostContent from './PostContent';
import PostHero from './PostHero';
import RelatedPosts from './RelatedPosts';

export {
	FeaturedPost,
	Hero,
	PostCard,
	PostContent,
	PostHero,
	RelatedPosts,
};

export const components = {
	featured_post: FeaturedPost,
	hero: Hero,
	featured_post: PostCard,
	post_content: PostContent,
	post_hero: PostHero,
	related_posts: RelatedPosts,
};
